apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-web
  namespace: prod
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: web
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: quay.io/shruti1988/webapp
~                                                                                                                                   
~                                                                                                                                   
~                                            
